language: php

matrix:
  include:
    - php: 7.0
      env: DEPENDENCIES='low'
    - php: 7.0

before_install:
  - composer self-update

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - ./bin/phpspec run --format=pretty
  - ./bin/phpunit --testdox